first pull
liveasy97/truckApi pull request #1
Opened 2021-04-15 15:38 UTC by badireddisatyasaivarun

2021-04-20 19:38 UTC, jsrub requested changes

2021-04-20 19:38 UTC, jsrub commented on .mvn/wrapper/MavenWrapperDownloader.java
> +/*
what is this file getting used for?

2021-04-20 19:38 UTC, jsrub commented on TruckBookingApplication.java
> +		System.out.println("first");
remove this

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Controller/TruckController.java
> +			return this.truckServiceImpl.addData(truckRequest);
since truck service is autowired you should write the service call statements as truckServiceImpl.addData(truckRequest);

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckPostResponse.java
> +public @Data class TruckPostResponse {
This class can be named TruckCreateResponse

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckPutRequest.java
> +public @Data class TruckPutRequest {
This can be renamed TruckUpdateRequest

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckResponse.java
> +	private UUID truckId;
change variable name to id. also these ids would be string - "truck:UUID" or "transporter:UUID".

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckResponse.java
> +	private String truckNo;
Add regex to validate truck no.

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckResponse.java
> +	private UUID IMEI;
I don't IMEI would be UUID.

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/entities/TruckData.java
> +	private UUID transporterId;
same comment as above about id.

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/entities/TruckData.java
> +	private UUID Imei;
same comment as above about IMEI

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/TruckApiApplication.java
> +		System.out.println("hello");
remove this

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +	public void deleteData(UUID id) {
add checks here

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +	public String updateData(UUID id,TruckPutRequest truckPutRequest) {
This method should send back Response Model instead of string

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		temp.setApproved(true);
set approve status as got in the request

2021-04-20 19:38 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +	}
Add checks here.

2021-04-20 20:33 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +	}
Thank you,
I will Correct all the required changes.

2021-04-21 16:51 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Model/TruckResponse.java
> +	private UUID truckId;
Which variable name should I change to Id, it should differentiate from transporter-Id and Truck-Id as well.

2021-04-21 17:29 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Model/TruckResponse.java
> +	private UUID truckId;
i meant for truckId . but lets keep it as truckId for now.

2021-04-22 16:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Controller/TruckController.java
> +		}
There should be no logic in the controller. Shift this to the service layer.

2021-04-22 16:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Controller/TruckController.java
> +//	}
remove commented code everywheer

2021-04-24 18:49 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			}
can you please explain what this code does. Also you can use simplified for loop instead of for(int i=0 ...)

2021-04-24 18:49 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +				}
what does this do?

2021-04-25 13:02 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			}
This code is to convert all the truckNo to no space format ex: "Rj 32 er 3333" to "Rj32er3333" as well as "Rj32 er 3333" to "Rj32er3333" like joining without any spaces.

2021-04-25 13:03 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +				}
This code to convert above no space format to specified spaced format to increase readability in the database.

2021-04-25 13:07 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			}
We have done this because while searching in the database "Rj 32 er 3333" is not considering same as "Rj32er3333", so we have converted all the different formats to single format.

2021-04-28 14:47 UTC, jsrub requested changes
major changes required on code refactoring. Tests don't seem to properly written. i.e you need to divide service layer and controller layer tests, but we can leave that for now.

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Controller/TruckController.java
> +//      localhost:8080/truck/?transporterId=df878007-80da-11e9-93dd-00163e004571&approved=false&pageNo=2
remove commented code

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Controller/TruckController.java
> +		//@PathVariable UUID truckId /{truckId}
remove commented code

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			truckCreateResponse.setStatus("Failed: Enter Correct Transporter Id");
add the error message to a constants file and use that here

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +
remove unnecessary spaces

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +//					System.out.println(1);
remove

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		}
instead of these checks you can add a regex to validate truck no.

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		}
please give a brief about what is happening here

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/entities/TruckData.java
> +	}
instead if these you can just use lombok and add @Data annotation at the top.

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +
there may be a better way to do this. You can query the db on the basis of truck id and transporter id and check if that object is non null. otherwise through this way you are making unnecessary calls to the db

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +				if(listTruckData.get(i).getTransporterId().equals(temp.getTransporterId()))
a better way to iterate everywhere is for(TruckData truckData: listTruckData)

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			Pageable p = PageRequest.of(pageNo,2);
why 2?

2021-04-28 14:47 UTC, jsrub commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			return truckDao.findAll();
lets remove this for now. I don't think we'll ever need to show all the trucks

2021-04-28 14:47 UTC, jsrub commented on TruckBookingApplication.java
> +		System.out.println("first");
remove this

2021-04-29 11:30 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			Pageable p = PageRequest.of(pageNo,2);
We can change them later on, right. The number of data visible in a single page, it will be a constant once app is fully built.

2021-04-29 11:37 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		}
Ok, I will try to use Regex and do it.

2021-04-29 11:38 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/entities/TruckData.java
> +	}
Yes, I have removed them by using @AllArgsConstructor and @NoArgsConstructor

2021-04-29 13:57 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		}
I have a doubt, I will use regex to validate the truck number, but How do I convert that truck number into a particular format as to store in a database. For example, "RJ-31-TR-2222" and "RJ 31 TR 2222" both are valid truck Numbers. But I need to store in only one format i.e: "RJ 31 TR 2222". How do I do that. Please Explain.

2021-05-01 09:38 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		return truckDao.findAll();
Suggested by Pranav.

2021-06-12 08:56 UTC, liveasy97 approved these changes

2021-06-12 08:56 UTC, merged