pr-2
liveasy97/truckApi pull request #3
Opened 2021-05-28 07:33 UTC by uckamdar59

Don't check tesing right now

2021-05-28 13:18 UTC, badireddisatyasaivarun reviewed
Correct These changes.

2021-05-28 13:18 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +
I haven't added a if condition if->(truckRequest.getTruckNo ==null), add it.

2021-05-28 13:18 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Constants/TruckConstants.java
> +	public static String updateSuccess = "Driver details Updated Succcessfully";
This should be Truck details not Drivers.

2021-05-28 13:18 UTC, badireddisatyasaivarun commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +
if some one tries to update transporterId or truckNo return an error message.

2021-06-01 18:39 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +
the tests can be named better to reflect what is actually being tested. 
can be like testCaseSuccess, testCaseFailed_invalidPhoneNo . Similarly the same scenario shouldn't be tested more than once. Ideally we should 1 success case with all the valid information and then lot of failure cases to verify  if the validations are working fine.

2021-06-01 18:41 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +package com.TruckApi.TruckApi;
same comment as mentioned below in service test cases. Please fix this and reply to this comment .I will review rest of the code after that.

2021-06-04 16:41 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Constants/TruckConstants.java
> +	public static String inCorrectTransporterId = "Failed: Enter Correct Transporter Id";
Must: Let's declare constants as final and keep the variable names in ALLCAPS with '_'

2021-06-04 17:25 UTC, arpitbhal12 reviewed
Apart from all the mentioned code review suggestions, please add proper exception handling across the codebase, I really didn't see any, ignore if its in plan, if not kindly add it in the future tasks.
Also please use some code formatting plugin in whatever IDEs you're using.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		data.setTruckId(truckId_temp);
If using lombok. setters are not required, You can @Builder, if don't know already, Cool stuff :)

2021-06-04 17:25 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		Optional<TruckData> d = Optional.ofNullable(truckDao.findByTruckId(id));
Please use descriptive namings of variables. very very important while working on a real project.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +		if(Objects.isNull(temp) || Objects.isNull(temp2)) {
Again descriptive variable names here, Temp or something like that should never be used in a project. it really reduces code readability for other developers.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		List<TruckData> listTruckData = new ArrayList<>();
Please use Arrays.asList() to create a list of objects of the below TruckData class objects.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		p = PageRequest.of(0,2);
I would use currentPage or just page instead of 'p' :)

2021-06-04 17:25 UTC, arpitbhal12 commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		TruckData t1 = new TruckData("id1","transporterId:0de885e0-5f43-4c68-8dde-b0f9ff81cb67","AP 32 AD 2222",false,null, 0, null, null, null);
Again Arrays.asList() here.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +			int l1 = Integer.valueOf(str.charAt(i));
FYI we don't need to parse the characters to ASCIIs, we can directly check like str.charAt(i) >= 'A' && str.charAt(i)<='Z' for capital alpphabets and similarly '0' and '9' for numbers.

2021-06-04 17:25 UTC, arpitbhal12 commented on src/main/java/com/TruckApi/TruckApi/Service/TruckServiceImpl.java
> +	}
Please remove all the truckNoUpdated builder logic from addData function and put that into a specific generateTruckNumber() function of its own.

2021-06-05 07:54 UTC, jsrub requested changes
added a few comments. Make the changes and reply to the comments. One general comment which can be followed here is that you should avoid code repetition. the methods should be kept as small as possible and any common tasks should be factored out.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +		String inputJson = this.mapToJson(truckRequest) ;
I think you should be able to use this function without the this keyword.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +		truckRequest.setTransporterId(null);
to reduce code repetition you can create util functions for creating truckRequest/Response

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +			String URI = "/truck";
you can store this variable along with other common variables in a constants file.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +	public void addDataFailed_invalidTruckNo() throws Exception{
correct the indentation of the code. you can use google java formatter for the same.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +
I don't think it makes much sense to write all the failure scenarios(that come from service) in controller tests. Since we are only getting mock response and not the actual response. In controller tests you should write only the test scenarios which can occur in controller itself.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +		truckData.setPassingWeight(300);
add a util function for doing all this.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +		String URI = "/truck/truckId:62cc8557-52cd-4742-a11e-276cc7bec12e";
store truck id in a variable and keep it in a common constants file.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckController.java
> +//	}
remove all the commented code if it is not being used.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckDao.java
> +package com.TruckApi.TruckApi;
Run these tests with h2 db and verify if these are running properly. Otherwise these seem fine

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckDao.java
> +
add util functions to create entity objects.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +
same comment as above. create common util functions for such tasks.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		assertEquals(truckCreateResponse.getStatus(),truckService.addData(truckRequest).getStatus());
you can possibly add another assert statement to verify if the data of the response is same as expected

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		truckRequest.setTransporterId(null);
along with null values this should also test the case where transporter id is invalid. i.e the id doesn't exist in our system.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		truckRequest.setTruckNo("");
same comment as above. Along with empty string we should be testing for actually invalid truck no. like XX 20 YY 9320. so that we can verify if our validations are working fine.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +		t2 = new TruckData(null,"transporterId:0de885e0-5f43-4c68-8dde-b0f9ff81cb67","He 23 re 4445",false,null, 0, null, null, null);
I don't think such a case should be possible since we should catch it in the service before it gets saved. Correct the test case as well the service logic if it is not handled there.

2021-06-05 07:54 UTC, jsrub commented on src/test/java/com/TruckApi/TruckApi/TestTruckService.java
> +			String truckId1 = "truckId:62cc8557-52cd-4742-a11e-276cc7abcde";
either keep these variables as global in the test class itself or create a separate constants/variable file.

2021-06-05 14:33 UTC, badireddisatyasaivarun commented on src/test/java/com/TruckApi/TruckApi/TestTruckDao.java
> +	public void testFindByTransporterIdAndTruckNo() {
This test case is not possible,  we can only have one unique combination of truckNo and transporterId

2021-06-05 14:33 UTC, badireddisatyasaivarun commented on src/test/java/com/TruckApi/TruckApi/TestTruckDao.java
> +
I guess here you should call 
TruckData getFromDb = truckDao.findByTruckId("truckId:0de885e0-5f43-4c68-8dde-b0f9ff12345");
this again.

2021-07-02 05:24 UTC, closed without merging